<template>
  <div class="home text-left">
    <ApiReference
      :configuration="{
        spec: { url: apiSpecUrl },
        proxy: 'https://api.scalar.com/request-proxy',
        footerBelowSidebar: false,
        theme: selectedTheme,
      }"
    />
  </div>
</template>

<script lang="ts">
import { ApiReference } from "@scalar/api-reference";

import { defineComponent } from "vue";
import lanaConfig from "../../lana.config.json";

export default defineComponent({
  name: "HomeView",
  components: {
    ApiReference,
  },
  data() {
    return {
      apiSpecUrl: "", // Initialize it with an empty string
      lanaConfig, // Add this line to include lanaConfig in the data
      selectedTheme: "", // dev's selected theme
    };
  },
  beforeMount() {
    this.selectedTheme = lanaConfig.theme || "default";

    // Get the current domain
    const currentDomain = window.location.origin;

    // Construct the full URL for your API spec
    this.apiSpecUrl = `${currentDomain}/resource/openapi-spec.yaml`;
  },
  mounted() {
    console.log("Dev theme from condig => ", this.selectedTheme);
    this.updateElementContentByClass(
      "darklight-reference-promo",
      "Generated by project-lana"
    );
  },
  methods: {
    updateElementContentByClass(className: string, content: string) {
      const elements = document.getElementsByClassName(className);
      for (let i = 0; i < elements.length; i++) {
        const element = elements[i] as HTMLAnchorElement;
        element.textContent = content;
        element.href = "https://github.com/FotieMConstant/project-lana";
        console.log(element);
      }
    },
  },
});
</script>
