<template>
  <div class="home text-left">
    <!-- <img class="mx-auto" alt="Vue logo" src="../assets/logo.png" /> -->
    <!-- <ApiReference specUrl="https://petstore.swagger.io/v2/swagger.json" /> -->
    <!-- <ApiReference
      :specUrl="apiSpecUrl"
      proxyUrl="https://api.scalar.com/request-proxy"
    /> -->
    <ApiReference
      :configuration="{
        spec: { url: apiSpecUrl },
        proxy: 'https://api.scalar.com/request-proxy',
        footerBelowSidebar: false,
      }"
    />
  </div>
</template>

<script lang="ts">
import { ApiReference } from "@scalar/api-reference";

import { defineComponent } from "vue";

export default defineComponent({
  name: "HomeView",
  components: {
    ApiReference,
  },
  data() {
    return {
      apiSpecUrl: "", // Initialize it with an empty string
    };
  },
  beforeMount() {
    // Get the current domain
    const currentDomain = window.location.origin;

    // Construct the full URL for your API spec
    this.apiSpecUrl = `${currentDomain}/resource/openapi-spec.yaml`;
  },
  mounted() {
    this.updateElementContentByClass(
      "darklight-reference-promo",
      "Generated by project-lana"
    );
  },
  methods: {
    updateElementContentByClass(className: string, content: string) {
      const elements = document.getElementsByClassName(className);
      for (let i = 0; i < elements.length; i++) {
        const element = elements[i] as HTMLAnchorElement;
        element.textContent = content;
        element.href = "https://github.com/FotieMConstant/project-lana";
        console.log(element);
      }
    },
  },
});
</script>
